### PR TITLE
Fix deprecation on graphql_definition ( Upgrade Graphql to 1.12.x)

### PR DESCRIPTION
**Pull request by alecslupu**
Upgrade graphql to address: 

* https://github.com/rmosolgo/graphql-ruby/pull/3765
* https://github.com/rmosolgo/graphql-ruby/pull/3750 
* 
Fixes :  #88

### CODE REVIEW

**Comment by gjtorikian** [comment]
Neat. Why the draft PR? It looks good to me.

**Comment by alecslupu** [comment]
@gjtorikian the PR is not  a draft.

**Comment by gjtorikian** [comment]
Ah sorry I was looking quickly and saw the timeline draft in your other repo. Thanks!

**Comment by gjtorikian** [comment]
Released as 2.1.0.

**Pull request merged**
