### PR TITLE
Replace sass with sassc

### PR DESCRIPTION
**Pull request by cselmer**
The `sass`gem is deprecated. This PR replaces `sass` with `sassc`

### CODE REVIEW

**Comment by gjtorikian** [comment]
Heya, I think this needs the `Gemfile` updated, too. Mind updating that? Thanks!

**Comment by cselmer** [comment]
@gjtorikian the`Gemfile` just references `graphql-docs.gemspec` for dependencies, so it shouldn't need to be updated.

**Comment by gjtorikian** [comment]
I guess I only quickly guessed at the problem, based on the current test failures the gem isn't being picked up:

```
GeneratorTest#test_that_erb_landing_pages_work:

Errno::ENOENT: No such file or directory - sassc

    /home/travis/build/gjtorikian/graphql-docs/lib/graphql-docs/generator.rb:108:in ``'

    /home/travis/build/gjtorikian/graphql-docs/lib/graphql-docs/generator.rb:108:in `generate'

    /home/travis/build/gjtorikian/graphql-docs/test/graphql-docs/generator_test.rb:166:in `test_that_erb_landing_pages_work'
```

**Comment by cselmer** [comment]
@gjtorikian It looks like a TravisCI issue not being able to find `libsass` - I took an unsuccessful quick stab at getting past the issue, but no dice. I'll circle back to this next week unless you have an idea of how to resolve.

**Pull request closed without merging**
